# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pledges.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0016_auto_20161103_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('confirmed', models.BooleanField(default=False, editable=False)),
                ('confirmation_nonce', models.CharField(default=pledges.models.generate_confirmation_nonce, editable=False, max_length=255)),
                ('review_status', models.CharField(choices=[('N', 'Needs Review'), ('A', 'Approved'), ('R', 'Rejected')], default='N', max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='sites.Site')),
            ],
        ),
    ]
