---
version: "3"
networks:
  app:
services:
  postgresql:
    image: postgres:9.5
    ports:
      - "127.0.0.1::5432"
    volumes:
      - ./:/django
    environment:
      POSTGRES_PASSWORD: securethenewspassword
      POSTGRES_USER: securethenews
      POSTGRES_DB: securethenewsdb
    user: postgres
    networks:
      app:
        aliases:
          - db

  node:
    build:
      context: .
      dockerfile: docker/DevNodeDockerfile
      args:
        USERID: ${UID:?err}
    volumes:
      - ./:/django
    working_dir: /django
    command: /bin/ash -c "npm install && touch .node_complete && npm run start"
    user: ${UID:?err}
    networks:
      - app

  django:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: docker/DevDjangoDockerfile
      args:
        USERID: ${UID:?err}
    depends_on:
      - node
      - postgresql
    environment:
      DEPLOY_ENV: dev
      DJANGO_ALLOWED_HOSTS: "app localhost"
      DJANGO_DB_HOST: db
      DJANGO_DB_PASSWORD: securethenewspassword
      DJANGO_DB_USER: securethenews
      DJANGO_DB_NAME: securethenewsdb
      DJANGO_DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: securethenews.settings.dev
    working_dir: /django
    volumes:
      - ./:/django
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      app:
        aliases:
          - app
