---
version: '3'
networks:
  app:
services:
  postgresql:
    image: postgres:9.5
    ports:
      - "5432"
    volumes:
      - ./:/django
    environment:
      POSTGRES_PASSWORD: securethenewspassword
      POSTGRES_USER: securethenews
      POSTGRES_DB: securethenewsdb
    user: postgres
    networks:
      app:
        aliases:
          - db
  django:
    build:
      context: .
      dockerfile: docker/ProdDjangoDockerfile
      args:
        # Ensure that this does *not* depend on the host env, and the
        # production CI and deployment can set it to whatever
        USERID: 12345
    image: quay.io/freedomofpress/securethenews
    read_only: true
    environment:
      DJANGO_ALLOWED_HOSTS: "app localhost"
      DEPLOY_ENV: prod
      DJANGO_DB_HOST: db
      DJANGO_DB_PASSWORD: securethenewspassword
      DJANGO_DB_USER: securethenews
      DJANGO_DB_NAME: securethenewsdb
      DJANGO_DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: securethenews.settings.production
      DJANGO_SECRET_KEY: 002b5d76a026c29190c50e610a73516cb277f0abd07ae6233fbbe86f655abc5a
      DJANGO_GCORN_UPLOAD_DIR: /dev/shm
      DJANGO_GCORN_HEARTBT_DIR: /dev/shm
      DJANGO_WHITENOISE: 'True'
    depends_on:
      - postgresql
    working_dir: /django
    volumes:
      - ${HOST_STATIC_DIR:-stn-django-media}:/django-media
    networks:
      app:
        aliases:
          - app
    ports:
      - "127.0.0.1:8000:8000"

volumes:
  stn-django-media:
