# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('scans', '0005_auto_20160803_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('site_url', models.CharField(help_text='Specify the domain name without the scheme, e.g. "example.com" instead of "https://example.com"', max_length=255, null=True, unique=True, verbose_name='URL')),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='page', to='scans.Site')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
