# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-02 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='name',
            field=models.CharField(default='changeme', max_length=255, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
