# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-13 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_populate_slug_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
