# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_enforce_unique_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='supports_https',
        ),
        migrations.AddField(
            model_name='scan',
            name='default_https',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='scan',
            name='downgrades_https',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='scan',
            name='live',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='score',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='scan',
            name='valid_https',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='scan',
            name='enforces_https',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='Slug'),
        ),
    ]
