# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0014_auto_20161020_0553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'get_latest_by': 'timestamp'},
        ),
        migrations.RemoveField(
            model_name='scan',
            name='strictly_forces_https',
        ),
    ]
