# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0016_auto_20161103_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='approved',
        ),
        migrations.AddField(
            model_name='pledge',
            name='status',
            field=models.CharField(choices=[('N', 'Needs Review'), ('A', 'Approved'), ('R', 'Rejected')], default='N', max_length=1),
        ),
    ]
