# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 01:41
from __future__ import unicode_literals

from django.db import migrations


def fix_downgrades_https_None_values(apps, schema_editor):
    Scan = apps.get_model("sites", "Scan")
    Scan.objects.filter(downgrades_https=None).update(downgrades_https=False)


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0016_auto_20161103_2350'),
    ]

    operations = [
        migrations.RunPython(fix_downgrades_https_None_values)
    ]
