# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 01:41
from __future__ import unicode_literals

from django.db import migrations


def fix_downgrades_https_None_values(apps, schema_editor):
    Scan = apps.get_model("sites", "Scan")
    for scan in Scan.objects.all():
        if scan.downgrades_https == None:
            scan.downgrades_https = False
            scan.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0016_auto_20161103_2350'),
    ]

    operations = [
        migrations.RunPython(fix_downgrades_https_None_values)
    ]
