# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import sites.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0018_auto_20161110_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='confirmation_nonce',
            field=models.CharField(default=sites.models.generate_confirmation_nonce, max_length=255),
        ),
        migrations.AddField(
            model_name='pledge',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
