# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='intro',
        ),
    ]
