# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-02 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_auto_20160802_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(help_text='Specify the domain name without the scheme, e.g. "example.com" instead of "https://example.com"', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
