# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-03 18:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_auto_20160802_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='scan',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 3, 18, 41, 42, 279764, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
