# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-30 18:31
from __future__ import unicode_literals

from django.db import migrations
from wagtail.core.rich_text import RichText


def convert_to_streamfield(apps, schema_editor):
    BlogPost = apps.get_model('blog', 'BlogPost')
    for post in BlogPost.objects.all():
        if post.body.raw_text and not post.body:
            post.body = [
                ('rich_text', RichText(post.body.raw_text)),
            ]
            post.save()


def convert_to_richtext(apps, schema_editor):
    BlogPost = apps.get_model('blog', 'BlogPost')
    for post in BlogPost.objects.all():
        if post.body.raw_text is None:
            raw_text = ''.join([
                child.value.source for child in post.body
                if child.block_type == 'rich_text'
            ])
            post.body = raw_text
            post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160930_1830'),
    ]

    operations = [
        migrations.RunPython(
            convert_to_streamfield,
            convert_to_richtext,
        ),
    ]
