# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='timestamp',
            new_name='submitted',
        ),
    ]
