# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('home', '0005_auto_20160914_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='button_url',
        ),
        migrations.AddField(
            model_name='contentpage',
            name='button_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
