# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contentpage_convert_richtextfield_to_streamfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='how_body',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='how_header',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sub_title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='why_body',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='why_header',
            field=models.TextField(default=''),
        ),
    ]
