# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20161108_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='how_body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='why_body',
            field=models.TextField(default=''),
        ),
    ]
