# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 01:13
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20161115_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock()), ('rich_text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.core.blocks.StructBlock((('quote', wagtail.core.blocks.TextBlock()), ('source', wagtail.core.blocks.CharBlock()), ('link', wagtail.core.blocks.URLBlock(required=False))))))),
        ),
    ]
