# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-20 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_auto_20161019_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='url',
            new_name='domain',
        ),
    ]
