# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-20 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_rename_site_url_to_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='default_https',
            new_name='defaults_to_https',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='enforces_https',
            new_name='strictly_forces_https',
        ),
        migrations.AddField(
            model_name='scan',
            name='hsts',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='scan',
            name='hsts_entire_domain',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='scan',
            name='hsts_max_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='hsts_preload_ready',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='scan',
            name='hsts_preloaded',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='domain',
            field=models.CharField(help_text='Specify the domain name without the scheme, e.g. "example.com" instead of "https://example.com"', max_length=255, unique=True, verbose_name='Domain Name'),
        ),
    ]
