# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-20 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0013_auto_20161020_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='curl_http',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='curl_http_www',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='curl_https',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='curl_https_www',
        ),
    ]
