# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-03 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_auto_20161024_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name']},
        ),
    ]
