# Generated by Django 2.2.10 on 2020-04-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0019_auto_20190917_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='Specify the twitter handle starting with "@"', max_length=16, verbose_name='Twitter Handle'),
        ),
    ]
