# Generated by Django 2.2.14 on 2020-08-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0020_site_twitter_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='onion_available',
            field=models.BooleanField(default=False),
        ),
    ]
