# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0020_site_sitecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='italy', editable=False, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
