# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0021_sitecategory_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='sitecategory',
            new_name='site_category',
        ),
    ]
