# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0022_auto_20171125_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
