# Generated by Django 2.2.14 on 2020-11-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0022_auto_20200910_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='onion_available',
            new_name='onion_location_header',
        ),
    ]
