# Generated by Django 2.1.11 on 2019-09-10 15:47

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('sites', '0023_auto_20171125_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, editable=False, unique=True, verbose_name='Slug')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': 'site categories',
            },
        ),
        migrations.RemoveField(
            model_name='sitecategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='site',
            name='site_category',
        ),
        migrations.DeleteModel(
            name='SiteCategory',
        ),
        migrations.AddField(
            model_name='site',
            name='regions',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select which leaderboard you would like this news site to appear on', related_name='_site_regions_+', to='sites.Region'),
        ),
    ]
